#!/usr/bin/bash

# Generatore progetti
#    - By FuoriProgramma

install_dir=$HOME/.Nproj

function crea_file {
	touch .projectile
	touch .gitignore
}

if [[ $1 == "Empty" ]]; then
	crea_file
	exit
fi

if [[ $1 == "C" ]]; then
	crea_file
	echo "Creazione progetto in C..."
	read -p "Nome del progetto: " nome
	read -p "Versione: " versione
	read -p "File contenente funzione main: " main
	mkdir build/
	mkdir bin/
	cp $install_dir/CMakeLists.txt .
	echo "build/" >> .gitignore
	echo "bin/" >> .gitignore
	echo ".*" >> .gitignore
	sed -i "s/NOME_PROGETTO/$nome/g" CMakeLists.txt
	sed -i "s/VERSIONE/$versione/g" CMakeLists.txt
	sed -i "s/FILE_MAIN/$main/g" CMakeLists.txt
	exit
fi

echo "Linguaggio non riconosciuto..."
